### ISSUE TITLE
Node JS: неиспользуемая локальная переменная в server.js

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#1]
var init = require('./config/init')()

Тут стоило либо сделать так:
var init = require('./config/init');
init();

либо вот так:
require('./config/init')();

Нет смысла заводить локальную переменную в подобных ситуациях.

**Comment by EugeneKapylski** [comment]
Очень многие моменты в коде, которые не связаны с непосредственно функциональностью чата, являются частью решения mean.js. Изначально структура проекта была сгенерирована используя yeoman.io. Эти файлы как правило я оставлял в первозданном виде, но они действительно содержат много моментов, которые следовало бы исправить. Этим занимаюсь в данный момент. Каждый твое комментарий безусловно очень поможет в этом. Я просмотрел все комментарии -  практически со всеми моментами согласен. Буду отвечать на них по мере исправления кода.

**Comment by EugeneKapylski** [comment]
Касательно этого комментария, удалил переменную init, буду лишь использовать выражение require('./config/init')();

**Comment by AlexMatusevich** [comment]
Хорошо, спасибо!
