### ISSUE TITLE
Node JS: нецелесообразное использование тернарного оператора

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#11]
var possibleUsername = providerUserProfile.username || ((providerUserProfile.email) ? providerUserProfile.email.split('@')[0] : '');

Такой код тяжело читать. Лучше использовать старый-добрый if...else :)

**Comment by EugeneKapylski** [comment]
Разбил на несколько строк, читабельность улучшилась.
Nут просто одной конструкцией if...else не отделаешься, а их вложенность тоже режет глаз.

**Comment by AlexMatusevich** [comment]
Про вложенность ```if...else``` согласен. Иногда бывает очень удобно написать helper-функцию, тогда получается что-то такое:
```
var possibleUsername = providerUserProfile.username || doSomething(providerUserProfile.email);
```
