### ISSUE TITLE
Node JS: не хватает скобок после if

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#12]
if (!user.additionalProvidersData) user.additionalProvidersData = {};

Стоит ставить фигурные скобки всегда, даже в случае единичного действия. Читабельность, унифицированность кода...

**Comment by AlexMatusevich** [comment]
if (err) return next(err);
if (!users) return next(new Error('Failed to load Users'));

**Comment by AlexMatusevich** [comment]
if (err) return next(err);
		if (!user) return next(new Error('Failed to load User ' + id));

**Comment by AlexMatusevich** [comment]
if (err) return next(err);

**Comment by AlexMatusevich** [comment]
if (err.errors[errName].message) message = err.errors[errName].message;

**Comment by AlexMatusevich** [comment]
if (err) return next(err);
		if (!messages) return next(new Error('Failed to get Messages'));

**Comment by AlexMatusevich** [comment]
if (window.location.hash === '#_=_') window.location.hash = '#!';

**Comment by EugeneKapylski** [comment]
Согласен, я тоже всегда фигурные скобки пишу, подправил все моменты.

**Comment by AlexMatusevich** [comment]
Хорошо.
