### ISSUE TITLE
Node JS: глобальная проблема в архитектуре

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#2]
Я могу ошибаться, т.к. еще не пытался запустить твое приложение без настроенной базы, но по коду создается впечатление, что твое приложение не запустится должным образом в таком случае. Приложение должно запускаться всегда, а вот в случае ошибки подключения к базе и подобного выводить на экран хотя бы какое-нибудь сообщение.

**Comment by EugeneKapylski** [comment]
Обращу внимание на этот момент. Просто при разработке я использовал cloud9 ide, там проблем не возникало, не брал во внимание случай ошибки соединения.
