### ISSUE TITLE
Gruntfile: лишние запятые

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#3]
options: {
livereload: true,
}

После livereload не нужна запятая.

**Comment by AlexMatusevich** [comment]
options: {
				csslintrc: '.csslintrc',
			},
			all: {
				src: watchFiles.clientCSS
			}

После csslintrc не нужна зяпятая.

**Comment by EugeneKapylski** [comment]
Точно, подправил
