### ISSUE TITLE
Node JS: именование файлов

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#5]
Во-первых, принято именовать файлы следующим образом: some-file-name.js. Но это дело вкуса.

Во-вторых, добавление к именам файлов постфиксов ('server', 'controller', 'models' и т.д.) излишне, т.к. структура папок у тебя информативна в должной степени, т.е. все модели лежат в папке 'models' и т.д.

**Comment by EugeneKapylski** [comment]
Такое именование изначально содержит mean.js, я уже не стал изменять все файлы проекта, стал следовать сложившейся структуре. С твоей поправкой согласен, в будущем буду иметь в виду

**Comment by AlexMatusevich** [comment]
Хорошо.
