### ISSUE TITLE
Node JS: неиспользуемая локальная переменная

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#6]
var message = null;
users.authentication.server.controller.js

**Comment by AlexMatusevich** [comment]
var message = null;
users.profile.server.controller.js

**Comment by AlexMatusevich** [comment]
var message = null;
messages.server.controller.js

**Comment by EugeneKapylski** [comment]
Удалил во всех указанных местах.
