### ISSUE TITLE
Node JS: не стоит явным образом присваивать undefined

### ISSUE THREAD

**Issue by AlexMatusevich** [EugeneKapylski/MEAN.Chat#7]
user.password = undefined;
user.salt = undefined;

Подобное встречается дважды.
Нужно либо в null устанавливать значения, либо использовать delete.

**Comment by AlexMatusevich** [comment]
user.resetPasswordToken = undefined;
						user.resetPasswordExpires = undefined;

**Comment by EugeneKapylski** [comment]
Подправил
